### ISSUE TITLE
Failure on pip install mahotas

### ISSUE THREAD

**Issue by thefancyyeller** [luispedro/mahotas#144]
Hello, 
I am trying to get mahotas working and have ran `pip install mahotas` and received the following error message:
```
...\pip-install-sccjngnr\mahotas_fd29d987e729417e8d8c8416f0142aee\mahotas\numpypp\numpy.hpp(11): fatal error C1083: Cannot open include file: 'numpy/ndarrayobject.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mahotas
Failed to build mahotas
ERROR: Could not build wheels for mahotas, which is required to install pyproject.toml-based projects
```
I am a bit lost as to what is going wrong. I know for a fact that I have numpy as I use it in my project, and I am certain that it is up-to-date. If anyone has any guidance on how I can fix this issue I would greatly appreciate it. I am running a (pretty vanilla) windows 10. I have had no issues with my other packages or pip, and I am sure that I have the latest version of pip.

**Comment by sprutner** [comment]
I am having the same issue using poetry on MacOS with an M1 chip.

```
[...]
      In file included from mahotas/numpypp/array.hpp:17:
      mahotas/numpypp/numpy.hpp:11:10: fatal error: 'numpy/ndarrayobject.h' file not found
      #include <numpy/ndarrayobject.h>
               ^~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mahotas
Failed to build mahotas
ERROR: Failed to build one or more wheels
```

**Comment by thefancyyeller** [comment]
Found out you just need to update python. The mahotas library doesn't tell
pip it doesn't support older python versions

**Comment by sprutner** [comment]
@thefancyyeller Which version of Python did you upgrade to?

**Comment by thefancyyeller** [comment]
I don't have the exact versions on hand to read to you bit I upgraded to
the latest python version. The issue is that Mahotas does not seem to
support older versions of python but it fails to tell Pip that information
so the compiled part of the build just fails.

You might be having a different issue but for me just upgrading to the
latest python version fixed it

**Comment by samaloney** [comment]
Same issue on arm64 for python 3.11 and 3.12 seems to work on 3.9 and 3.10

Relevant output simliar for 3.11
```
copying mahotas/demos/data/luispedro.jpg -> build/lib.macosx-14-arm64-cpython-312/mahotas/demos/data
      running build_ext
      building 'mahotas._bbox' extension
      creating build/temp.macosx-14-arm64-cpython-312
      creating build/temp.macosx-14-arm64-cpython-312/mahotas
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -DPY_ARRAY_UNIQUE_SYMBOL=Mahotas_PyArray_API_Symbol -I[] -I/Users/sm/.virtualenvs/test312/include -I/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c mahotas/_bbox.cpp -o build/temp.macosx-14-arm64-cpython-312/mahotas/_bbox.o
      In file included from mahotas/_bbox.cpp:11:
      In file included from mahotas/numpypp/array.hpp:17:
      mahotas/numpypp/numpy.hpp:11:10: fatal error: 'numpy/ndarrayobject.h' file not found
      #include <numpy/ndarrayobject.h>
               ^~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
```

**Comment by Czaki** [comment]
this problem is caused by lack of declaration of numpy as build dependecy of mahotas.

**Comment by paulmueller** [comment]
Also note that there are no binary releases for 1.14.4 when compared to 1.14.3
https://pypi.org/project/mahotas/1.4.14/#files
https://pypi.org/project/mahotas/1.4.13/#files

**Comment by Czaki** [comment]
> Also note that there are no binary releases for Windows/macOS for 1.14.4 when compared to 1.14.3

Yes, because these workflows has been failed:

https://github.com/luispedro/mahotas/actions/runs/8405184839
https://github.com/luispedro/mahotas/actions/runs/8405184838

I have opened PR to fix all of these problems, but it is waiting for review:

https://github.com/luispedro/mahotas/pull/147

**Comment by Czaki** [comment]
The minimal change required is to add `pyproject.toml` file with the following content:

```toml
[build-system]
requires = ["setuptools", "numpy"]
# When build with numpy>=1.25 the resulted binary wheel is compatybile with numpy >=1.16
build-backend = "setuptools.build_meta"
```

It will allow compiling packages locally.

**Comment by luispedro** [comment]
FYI, I merged #147

**Comment by Czaki** [comment]
When we could expect new release?

**Comment by luispedro** [comment]
In a bit, I'll do a release

**Comment by luispedro** [comment]
Just running tests on a separate branch before committing to `main`: https://github.com/luispedro/mahotas/tree/test_1_4_15

**Comment by Czaki** [comment]
It is on pypi :tada:

**Comment by luispedro** [comment]
I am closing. Please re-open if still relevant
